### ISSUE TITLE
update_policy documentation seems incorrect

### ISSUE THREAD

**Issue by daisy1754** [terraform-google-modules/terraform-google-vm#123]
Per https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_region_instance_group_manager#rolling_update_policy , only minimal_action and type are required field for update_policy. However when I run terraform plan with following:

```
module "my_mig" {
  source            = "terraform-google-modules/vm/google//modules/mig"
  version           = "5.1.0"
  instance_template = module.my_module.self_link
  region            = var.region
  target_size       = var.instance_count
  update_policy = [{
    type            = "PROACTIVE"
    minimal_action  = "REPLACE"
    max_surge_fixed = 1 
  }]
  hostname          = "my_host"
  named_ports = [
    {
      name = "http",
      port = "80"
    }
  ]
  network = "default"
}
```

I got following error message:
```
The given value is not suitable for child module variable "update_policy"
defined at
.terraform/modules/my_module.my_mig/modules/mig/variables.tf:71,1-25:
element 0: attributes "instance_redistribution_type", "max_surge_percent",
"max_unavailable_fixed", "max_unavailable_percent", and "min_ready_sec" are
required.
```

**Comment by AliAllomani** [comment]
because the variable `update_policy` has the type of map of object, all the object keys have to be defined.

https://github.com/terraform-google-modules/terraform-google-vm/blob/ae4d7777958fe4238d96191a3aa7c7deab996fd1/modules/mig/variables.tf#L71-L84

a better approach here maybe is to modify `update_policy` to have only the required values, and use `lookup` within the resources to define the default values for the optional keys

```hcl
variable "update_policy" {
  description = "The rolling update policy. https://www.terraform.io/docs/providers/google/r/compute_region_instance_group_manager.html#rolling_update_policy"
  type = list(object({
    minimal_action               = string
    type                         = string
  }))
  default = []
}
```
I think there is an experimental feature in terraform v0.14.0-rc1 that allows us to define optional keys for the variables of type object.

https://github.com/hashicorp/terraform/releases

> module_variable_optional_attrs: When declaring an input variable for a module whose type constraint (type argument) contains an object type constraint, the type expressions for the attributes can be annotated with the experimental optional(...) modifier.
Marking an attribute as "optional" changes the type conversion behavior for that type constraint so that if the given value is a map or object that has no attribute of that name then Terraform will silently give that attribute the value null, rather than returning an error saying that it is required. The resulting value still conforms to the type constraint in that the attribute is considered to be present, but references to it in the recieving module will find a null value and can act on that accordingly.

**Comment by SamCloudbakers** [comment]
Hopefully bumping this - ran into it today.
