### ISSUE TITLE
Add the option to use name instead of name_prefix in instance_template

### ISSUE THREAD

**Issue by denissimonovski** [terraform-google-modules/terraform-google-vm#183]
I need an instance_template named as the variable, without appending of any UID to the name. I can work on this, to add this feature. Is it ok to add this to the instance_template module?

**Comment by morgante** [comment]
What's your use case for needing the `name` instead of the `name_prefix`?

**Comment by denissimonovski** [comment]
I will need to import instance templates already deployed manually without UID appended to the name.

**Comment by doniz** [comment]
I was experienced the same, but it was way faster to just recreate them and apply on instance group to rollout servers.

**Comment by 210rain** [comment]
My use case for this module would involve manging multiple stateful managed instance groups over multiple projects. The issue I'm facing currently with name_prefix is that it looks like the autogenerated part of the name is a time stamp, which is regenerated on every `terraform apply`. 

Since the name is autogenerated on every `terraform apply`, every apply is taking my stateful managed instance group offline briefly to update to the new (functionally identical) template. This isn't a problem for dev but would cause unnecessary downtime for prod.

Is there a workaround for this _other than_ changing the `name_prefix` to `name` or setting a lifecycle policy to ignore name changes?

**Comment by jlenuffgsoi** [comment]
I'm facing the same issue when I do an `apply`.
How can we avoid template and MIG replacement due to this timestamp on name ?
