### ISSUE TITLE
Stateful IP Addresess

### ISSUE THREAD

**Issue by cydergoth** [terraform-google-modules/terraform-google-vm#280]
### TL;DR

MiGs now support stateful IP Addresses like stateful disks. I don't see a way to set that in this module.

**Comment by disusered** [comment]
I also need this in order to configure the "Group Config" from the module:

![image](https://user-images.githubusercontent.com/246254/213614310-deb3db6e-4ba3-48ff-9c9e-9252e73e5918.png)

There is also a lifecycle option for stateful MIGs that is useful when working with them:

![image](https://user-images.githubusercontent.com/246254/213614426-e9230909-8b36-4d13-903c-888562cd59d4.png)

Both of these would be very useful to be able to define upfront!

**Comment by ericyz** [comment]
Raised PR to support this - https://github.com/terraform-google-modules/terraform-google-vm/pull/297

**Comment by ericyz** [comment]
Closed by https://github.com/terraform-google-modules/terraform-google-vm/pull/297
