### ISSUE TITLE
Property "static_ips" isn't use in compute instance

### ISSUE THREAD

**Issue by stefiix92** [terraform-google-modules/terraform-google-vm#365]
### TL;DR

The variable `static_ips` which exists on the module level, isn't used inside the module at all.

### Expected behavior

Either remove the variable (it's confusing) or make it work

### Terraform Configuration

```hcl
module "relay_instance" {
  source              = "terraform-google-modules/vm/google//modules/compute_instance"
  hostname            = "asd"
  add_hostname_suffix = false
  instance_template   = module.template.self_link
  zone                = random_shuffle.zone.result[0]
  deletion_protection = false
  static_ips          = [google_compute_address.ip_address.address]
}
```

### Terraform Version

```sh
v1.5.7
```

**Comment by fernandoiury** [comment]
@stefiix92 I'm having another issue related to static_ips (because in my case I need two interfaces from different subnetworks) but for your case static ips should work if you pass var.netwok and var.subnetwork

See the following line, it's checking if you have these two vars and then it uses var.static_ips if they exist: https://github.com/terraform-google-modules/terraform-google-vm/blob/05cf9996c3c7926d61a83038218cdba594ced5b6/modules/compute_instance/main.tf#L29
